site_name: "Oliver"
repo_url: "https://github.com/stjudecloud/oliver"

site_description: "An opinionated Cromwell orchestration manager."
site_author: "St. Jude Cloud"
copyright: "Â© 2020 St. Jude Children's Research Hospital"

google_analytics: ["UA-107924368-1", "stjudecloud.github.io/oliver"]

nav:
  - "Home": "index.md"
  - "Getting Started":
    - "Configuration": "getting-started/configuration.md"
    - "Submitting Jobs": "getting-started/submit-jobs.md"
    - "Monitoring Jobs": "getting-started/monitor-jobs.md"
  - "Integrations":
    - "Azure": "integrations/azure.md"
    - "AWS": "integrations/aws.md"
  - "Advanced Guides":
    - "advanced-guides/output-prefixing.md"

theme: yeti